In [119]:
import pandas as pd

In [120]:
dados= pd.read_csv('C:/Users/biankac/Downloads/dados_vendas_.csv', decimal='.')
dados

    data_venda   produto  quantidade  preco_unitario  valor_total
0   2026-01-01   Jaqueta         5.0            50.0        250.0
1   2026-01-02      Meia         1.0            20.0         20.0
2   2026-01-03     Tênis         1.0           250.0        250.0
3   2026-01-04      Meia         0.0           250.0          0.0
4   2026-01-05      Meia         1.0           250.0        250.0
5   2026-01-06     Calça         4.0             NaN          NaN
6   2026-01-07     Tênis         1.0            20.0         20.0
7   2026-01-08     Tênis         3.0             NaN          NaN
8   2026-01-09     Tênis         3.0             NaN          NaN
9   2026-01-10      Meia         NaN            20.0          NaN
10  2026-01-11   Jaqueta         3.0            20.0         60.0
11  2026-01-12     Tênis         NaN            20.0          NaN
12  2026-01-13       NaN         3.0            20.0         60.0
13  2026-01-14      Meia         4.0           250.0       1000.0
14  2026-01-15     Calça         NaN           120.0          NaN
15  2026-01-16   Jaqueta         2.0           120.0        240.0
16  2026-01-17       NaN         5.0            20.0        100.0
17  2026-01-18       NaN         0.0           120.0          0.0
18  2026-01-19     Calça         3.0           120.0        360.0
19  2026-01-20   Jaqueta         1.0            20.0         20.0
20  2026-01-21      Meia         3.0           120.0        360.0
21  2026-01-22  Camiseta         1.0             NaN          NaN
22  2026-01-23   Jaqueta         5.0            50.0        250.0
23  2026-01-24     Calça         5.0            50.0        250.0
24  2026-01-25       NaN         5.0            20.0        100.0
25  2026-01-26      Meia         1.0           250.0        250.0
26  2026-01-27   Jaqueta         3.0            20.0         60.0
27  2026-01-28  Camiseta         5.0           250.0       1250.0
28  2026-01-29  Camiseta         4.0            50.0        200.0
29  2026-01-30     Tênis         NaN            20.0          NaN
30  2026-01-31     Tênis         1.0             NaN          NaN
31  2026-02-01     Calça         1.0           120.0        120.0
32  2026-02-02   Jaqueta         3.0           250.0        750.0
33  2026-02-03   Jaqueta         1.0           120.0        120.0
34  2026-02-04       NaN         1.0           120.0        120.0
35  2026-02-05       NaN         5.0            20.0        100.0
36  2026-02-06       NaN         3.0           120.0        360.0
37  2026-02-07     Tênis         5.0             NaN          NaN
38  2026-02-08   Jaqueta         NaN           120.0          NaN
39  2026-02-09   Jaqueta         NaN            20.0          NaN
40  2026-02-10  Camiseta         5.0             NaN          NaN
41  2026-02-11     Tênis         NaN            50.0          NaN
42  2026-02-12      Meia         3.0           120.0        360.0
43  2026-02-13     Tênis         0.0            20.0          0.0
44  2026-02-14      Meia         5.0            50.0        250.0
45  2026-02-15  Camiseta         4.0            50.0        200.0
46  2026-02-16     Calça         4.0           250.0       1000.0
47  2026-02-17   Jaqueta         1.0             NaN          NaN
48  2026-02-18  Camiseta         NaN           120.0          NaN
49  2026-02-19   Jaqueta         4.0            20.0         80.0

In [121]:
dados.head(5) #visualizar aprenas primeiras linhas

   data_venda  produto  quantidade  preco_unitario  valor_total
0  2026-01-01  Jaqueta         5.0            50.0        250.0
1  2026-01-02     Meia         1.0            20.0         20.0
2  2026-01-03    Tênis         1.0           250.0        250.0
3  2026-01-04     Meia         0.0           250.0          0.0
4  2026-01-05     Meia         1.0           250.0        250.0

In [122]:
dados.dropna() #remove valores nulos

    data_venda   produto  quantidade  preco_unitario  valor_total
0   2026-01-01   Jaqueta         5.0            50.0        250.0
1   2026-01-02      Meia         1.0            20.0         20.0
2   2026-01-03     Tênis         1.0           250.0        250.0
3   2026-01-04      Meia         0.0           250.0          0.0
4   2026-01-05      Meia         1.0           250.0        250.0
6   2026-01-07     Tênis         1.0            20.0         20.0
10  2026-01-11   Jaqueta         3.0            20.0         60.0
13  2026-01-14      Meia         4.0           250.0       1000.0
15  2026-01-16   Jaqueta         2.0           120.0        240.0
18  2026-01-19     Calça         3.0           120.0        360.0
19  2026-01-20   Jaqueta         1.0            20.0         20.0
20  2026-01-21      Meia         3.0           120.0        360.0
22  2026-01-23   Jaqueta         5.0            50.0        250.0
23  2026-01-24     Calça         5.0            50.0        250.0
25  2026-01-26      Meia         1.0           250.0        250.0
26  2026-01-27   Jaqueta         3.0            20.0         60.0
27  2026-01-28  Camiseta         5.0           250.0       1250.0
28  2026-01-29  Camiseta         4.0            50.0        200.0
31  2026-02-01     Calça         1.0           120.0        120.0
32  2026-02-02   Jaqueta         3.0           250.0        750.0
33  2026-02-03   Jaqueta         1.0           120.0        120.0
42  2026-02-12      Meia         3.0           120.0        360.0
43  2026-02-13     Tênis         0.0            20.0          0.0
44  2026-02-14      Meia         5.0            50.0        250.0
45  2026-02-15  Camiseta         4.0            50.0        200.0
46  2026-02-16     Calça         4.0           250.0       1000.0
49  2026-02-19   Jaqueta         4.0            20.0         80.0

In [123]:
#renomeando colunas
novos_nomes= {            
    'data_venda': 'venda'
}
dados_renomeados = dados.rename(columns=novos_nomes)
dados_renomeados.dropna()
dados_renomeados.head()

        venda  produto  quantidade  preco_unitario  valor_total
0  2026-01-01  Jaqueta         5.0            50.0        250.0
1  2026-01-02     Meia         1.0            20.0         20.0
2  2026-01-03    Tênis         1.0           250.0        250.0
3  2026-01-04     Meia         0.0           250.0          0.0
4  2026-01-05     Meia         1.0           250.0        250.0

In [124]:
dados.loc[0, 'preco_unitario'] = '150.0' #alterar valor em uma linha, index, nome da coluna e alteração 
dados.head()

C:\Users\biankac\AppData\Local\Temp\ipykernel_6960\2671510617.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '150.0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  dados.loc[0, 'preco_unitario'] = '150.0' #alterar valor em uma linha, index, nome da coluna e alteração

   data_venda  produto  quantidade preco_unitario  valor_total
0  2026-01-01  Jaqueta         5.0          150.0        250.0
1  2026-01-02     Meia         1.0           20.0         20.0
2  2026-01-03    Tênis         1.0          250.0        250.0
3  2026-01-04     Meia         0.0          250.0          0.0
4  2026-01-05     Meia         1.0          250.0        250.0

In [125]:
#alterando uma coluna especifica de todos os produtos com mesmo nome
dados.loc[dados['produto'] == 'Jaqueta', 'preco_unitario'] = 150.0 
dados.loc[dados['produto'] == 'Meia', 'preco_unitario'] = 20.0
dados.loc[dados['produto'] == 'Tênis', 'preco_unitario'] = 200.0
dados.loc[dados['produto'] == 'Camiseta', 'preco_unitario'] = 80.0
dados.dropna()
dados.head()

   data_venda  produto  quantidade preco_unitario  valor_total
0  2026-01-01  Jaqueta         5.0          150.0        250.0
1  2026-01-02     Meia         1.0           20.0         20.0
2  2026-01-03    Tênis         1.0          200.0        250.0
3  2026-01-04     Meia         0.0           20.0          0.0
4  2026-01-05     Meia         1.0           20.0        250.0

In [126]:
#alterando a quatidade do index 3 
dados.loc[3, 'quantidade'] = '3'
dados.head()

C:\Users\biankac\AppData\Local\Temp\ipykernel_6960\1565021191.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  dados.loc[3, 'quantidade'] = '3'

   data_venda  produto quantidade preco_unitario  valor_total
0  2026-01-01  Jaqueta        5.0          150.0        250.0
1  2026-01-02     Meia        1.0           20.0         20.0
2  2026-01-03    Tênis        1.0          200.0        250.0
3  2026-01-04     Meia          3           20.0          0.0
4  2026-01-05     Meia        1.0           20.0        250.0

In [127]:
#precisei converter a quatidade para floeat pois esta em str, assim a soma deu certo 
dados['quantidade']=dados['quantidade'].astype(float)

In [128]:
#somando a quatidade + preco_unitario para dar preço total 
dados['valor_total'] = dados['quantidade'] * dados['preco_unitario']
dados.dropna()
dados.head()

   data_venda  produto  quantidade preco_unitario valor_total
0  2026-01-01  Jaqueta         5.0          150.0       750.0
1  2026-01-02     Meia         1.0           20.0        20.0
2  2026-01-03    Tênis         1.0          200.0       200.0
3  2026-01-04     Meia         3.0           20.0        60.0
4  2026-01-05     Meia         1.0           20.0        20.0

In [129]:
#total e media das vendas 
total=dados['valor_total'].sum()
print(f'O total de vendas é: {total}')
media= total / len(dados['valor_total'])
print(f'A média de vendas é: {media}')

O total de vendas é: 11510.0
A média de vendas é: 230.2

In [130]:
#total de quantidade e total do valor de cada produto vendido
total_produto=dados.groupby('produto')['quantidade'].sum()
print(f'O total de cada produto vendido foi: {total_produto}')
t_prod= dados.groupby('produto')['valor_total'].sum()
print(f'O preço total de cada produto vendido foi: {t_prod}')

O total de cada produto vendido foi: produto
Calça       17.0
Camiseta    19.0
Jaqueta     28.0
Meia        21.0
Tênis       14.0
Name: quantidade, dtype: float64
O preço total de cada produto vendido foi: produto
Calça       1730.0
Camiseta    1520.0
Jaqueta     4200.0
Meia         420.0
Tênis       2800.0
Name: valor_total, dtype: object

In [131]:
#média de do valor cada produto vendido 
media_prod= dados.groupby('produto')['preco_unitario'].mean()
print(f'Média do valor de cada produto vendido: {media_prod}')

Média do valor de cada produto vendido: produto
Calça       132.0
Camiseta     80.0
Jaqueta     150.0
Meia         20.0
Tênis       200.0
Name: preco_unitario, dtype: object